name: Unit-Tests

trigger: none

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

variables:
  node_version: '22.14.0' # SPFx 1.21.1

steps:
  - task: UseNode@1
    inputs:
      version: '$(node_version)'
    displayName: 'Use Node $(node_version)'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npm test -- --ci --reporters=default --reporters=jest-junit
    displayName: 'Run Jest tests'
    continueOnError: false

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/junit.xml'
      testRunTitle: 'Jest Unit Tests'
      failTaskOnFailedTests: true
